# Generated by Django 3.2.4 on 2022-07-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blogmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/products_image'),
        ),
    ]
