# Generated by Django 3.2.4 on 2022-07-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productsmodel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
    ]
